
#path_classifiers:
#  generated:
#    - exclude: cpp_src/**/*

extraction:
  cpp:
    prepare:
      packages: 
        - liblua5.2-dev
        - libpq-dev
        - postgresql-server-dev-all
        - libao-dev
        - libavutil-dev
        - libavformat-dev
        - libavcodec-dev
        - libswscale-dev
        - libdatrie-dev
        - libfann-dev
        - libfftw3-dev
        - libfuse-dev
        - libgmp-dev
        - libmpfr-dev
        - libgstreamer1.0-dev
        - libgsl-dev
        - libgtk-3-dev
        - libmicrohttpd-dev
        - libglm-dev
        - libglib2.0-dev
        - libmono-2.0-dev
        - mono-runtime-sgen
        - libmpg123-dev
        - libnanomsg-dev
        - libopencv-dev
        - libportaudio2
        - libprotobuf-c-dev
        - libraw-dev
        - libsnappy-dev
        - libsqlite3-dev
        - libssh2-1-dev
        - libwebsockets-dev
        - libva-dev
        - libvlc-dev
        - freeglut3-dev
        - libglew-dev
    configure:
      command:
        - git clone --branch=master https://github.com/izuzanak/cont.git $LGTM_WORKSPACE/cont
        - cd $LGTM_WORKSPACE/cont/build
        - cmake -DCMAKE_INSTALL_PREFIX=install ..
        - make
        - make install
    index:
      build_command:
        - export PATH=$PATH:$LGTM_WORKSPACE/cont/build/install/bin
        - cd $LGTM_SRC/cpp_src/gen
        - cmake ..
        - cd proc_files
        - mkdir -p build
        - cd build
        - cmake ..
        - make

