
language: cpp
compiler: gcc
os: linux
dist: bionic

install:
  - git clone --branch=master https://github.com/izuzanak/cont.git ~/build/izuzanak/cont

  - cd ~/build/izuzanak/cont/build
  - cmake ..
  - make
  - sudo make install

script:
  - cd ~/build/izuzanak/uclang/build
  - cmake ..
  - make
  - sudo make install

