
language: cpp
compiler: gcc
os: linux
dist: bionic

before_install:
  - >
    sudo apt-get -y install
    liblua5.2-dev
    libpq-dev
    postgresql-server-dev-all
    libao-dev
    libavutil-dev
    libavformat-dev
    libavcodec-dev
    libswscale-dev
    libdatrie-dev
    libfann-dev
    libfftw3-dev
    libfuse-dev
    libgmp-dev
    libmpfr-dev
    libgstreamer1.0-dev
    libgsl-dev
    libgtk-3-dev
    libmicrohttpd-dev
    libglm-dev
    libglib2.0-dev
    libmono-2.0-dev
    mono-runtime-sgen
    libmpg123-dev
    libnanomsg-dev
    libopencv-dev
    libportaudio2
    libprotobuf-c-dev
    libraw-dev
    libsnappy-dev
    libsqlite3-dev
    libssh2-1-dev
    libwebsockets-dev
    libva-dev
    libvlc-dev
    freeglut3-dev
    libglew-dev

install:
  - git clone --branch=master https://github.com/izuzanak/cont.git ~/build/izuzanak/cont

  - cd ~/build/izuzanak/cont/build
  - cmake ..
  - make
  - sudo make install

script:
  - cd ~/build/izuzanak/uclang/build
  - cmake ..
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib/uclang

  - cd ~/build/izuzanak/uclang/uclang/examples
  - source prepare.sh
  - cd test
  - uclang test.ucl snapshot:test

  - cd ~/build/izuzanak/uclang/uclang_build
  - bash scripts/docu_gen.sh

