c_enabled = [
    True,  # LIB_BASE
    True,  # LIB_FTGL
    True,  # LIB_NODE
    True,  # UCLANG
    True,  # NODE
    True,  # ENCIPHER
    True,  # MOD_BASE
    True,  # MOD_SYS
    True,  # MOD_TIME
    True,  # MOD_LANG
    True,  # MOD_PACK
    True,  # MOD_CIPHER
    True,  # MOD_PARSER
    True,  # MOD_MATH
    True,  # MOD_PSQL
    True,  # MOD_SQLITE
    True,  # MOD_HTTP
    True,  # MOD_WEBSOCKET
    True,  # MOD_CURL
    True,  # MOD_UCF
    True,  # MOD_UCTCN
    True,  # MOD_ADAPTRAIN
    True,  # MOD_FTP
    True,  # MOD_SSH2
    True,  # MOD_GCRYPT
    True,  # MOD_ICONV
    True,  # MOD_JIT
    False, # MOD_LIGHTNING
    True,  # MOD_LLVM
    True,  # MOD_AV
    True,  # MOD_AO
    True,  # MOD_MPG
    True,  # MOD_PORTAUDIO
    True,  # MOD_GSTREAMER
    True,  # MOD_IMAGE
    True,  # MOD_OPENCV
    True,  # MOD_DOCU
    True,  # MOD_GLUT
    True,  # MOD_GLEW
    True,  # MOD_GL
    True,  # MOD_FTGL
    False, # MOD_VG
    False, # MOD_IMXEGL
    True,  # MOD_SNMP
    False, # MOD_COMELM
    True,  # MOD_UCPAS
    True,  # MOD_NODE
    False, # MOD_DDB
    True,  # MOD_CONTAINERS
    True,  # MOD_GRAPH
    True,  # MOD_JSON
    True,  # MOD_XML
    True,  # MOD_SOAPCL
    True,  # MOD_SOAPSRV
    True,  # MOD_PYTHON
    True,  # MOD_V8
    True,  # MOD_UV
    True,  # MOD_FUSE
    False, # MOD_ANDROID
    False, # MOD_NACL
]
