c_enabled = [
    True,  # LIB_BASE
    False, # LIB_FTGL
    True,  # LIB_NODE
    True,  # UCLANG
    True,  # NODE
    True,  # ENCIPHER
    True,  # MOD_BASE
    True,  # MOD_SYS
    True,  # MOD_TIME
    True,  # MOD_LANG
    True,  # MOD_PACK
    True,  # MOD_CIPHER
    True,  # MOD_PARSER
    False, # MOD_MATH
    False, # MOD_PSQL
    False, # MOD_SQLITE
    False, # MOD_HTTP
    False, # MOD_WEBSOCKET
    False, # MOD_CURL
    False, # MOD_UCF
    False, # MOD_UCTCN
    False, # MOD_ADAPTRAIN
    True,  # MOD_FTP
    True,  # MOD_SSH2
    True,  # MOD_GCRYPT
    True,  # MOD_ICONV
    False, # MOD_JIT
    False, # MOD_LIGHTNING
    False, # MOD_LLVM
    False, # MOD_AV
    False, # MOD_AO
    False, # MOD_MPG
    False, # MOD_PORTAUDIO
    False, # MOD_GSTREAMER
    True,  # MOD_IMAGE
    False, # MOD_OPENCV
    True,  # MOD_DOCU
    False, # MOD_GLUT
    False, # MOD_GLEW
    False, # MOD_GL
    False, # MOD_FTGL
    False, # MOD_VG
    False, # MOD_IMXEGL
    False, # MOD_SNMP
    False, # MOD_COMELM
    False, # MOD_UCPAS
    True,  # MOD_NODE
    False, # MOD_DDB
    True,  # MOD_CONTAINERS
    True,  # MOD_GRAPH
    True,  # MOD_JSON
    True,  # MOD_XML
    False, # MOD_SOAPCL
    False, # MOD_SOAPSRV
    False, # MOD_PYTHON
    False, # MOD_V8
    False, # MOD_UV
    False, # MOD_FUSE
    False, # MOD_ANDROID
    False, # MOD_NACL
]
